spring.application.name=ArquiHexaCrud

spring.datasource.url=jdbc:mysql://localhost:3306/uni_arqapp
spring.datasource.username=root
spring.datasource.password=Pruebas123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080